### ISSUE TITLE
[PE-D][Tester C] addtags function does not update the contact's tags in selected view

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-2/tp#114]
![image.png](https://raw.githubusercontent.com/NewtonKoh/ped/main/files/dccec041-cfeb-4484-b6b3-731de15f9e33.png)

The addtags function does not update the selected contact's tags. So we run into a situation where the contact's tags in the list view differs from the contact's tags in the selected view.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: NewtonKoh/ped#1

**Comment by ziyang27** [comment]
Planned Enhancement
