### ISSUE TITLE
[PE-D][Tester D] AddCommand example message invalid format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-2/tp#119]
Typing an invalid addCommand format produced an error message for user feedback. However, the example given in the error message is also invalid if copy pasted into the command text field.

Steps to reproduce:
1) type `add`
*this would typically produce an invalid format error message
2) highlight and copy paste the command line **after** `Example: `

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: dabzpengu/ped#1

**Comment by ziyang27** [comment]
<img width="311" alt="image" src="https://github.com/AY2324S2-CS2103T-F13-2/tp/assets/122247192/c88352a7-06f7-4f04-ae3d-f9ff9aeaea89">

Just checked the website, and this can be fixed 😄
