### ISSUE TITLE
[PE-D][Tester C] Selected contact still displays after cleared command is run

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-2/tp#124]
![image.png](https://raw.githubusercontent.com/NewtonKoh/ped/main/files/eba5d277-00f3-49cc-956d-b415ae8fe9cc.png)

All contacts have been cleared here but John Doe is still being displayed

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: NewtonKoh/ped#5

**Comment by ziyang27** [comment]
Planned Enhancement
