### ISSUE TITLE
[PE-D][Tester C] example given in error message is in wrong format

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-2/tp#140]
![image.png](https://raw.githubusercontent.com/NewtonKoh/ped/main/files/8d7e2a23-a62b-4d64-80df-a545af335526.png)

example given in error message is in the wrong format and does not work

![image.png](https://raw.githubusercontent.com/NewtonKoh/ped/main/files/d8960b00-a329-4d5c-8137-6ddc0d247d7a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: NewtonKoh/ped#8

**Comment by ziyang27** [comment]
Duplicated
