### ISSUE TITLE
[PE-D][Tester B] Mismatch in how empty tag is handled for findtagsor or possibly findtagsand command relative to other tag related command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-2/tp#145]
Seeing as how, one could use `t/ ` to change all tags to nothing in the `edit` command, a user may expect the `findtagsor` or even `findtagsand` to also work with an empty space as the input for the tag parameter, to find contacts that do not have a tag. However, in this case, the app displayed an invalid command format error message.

![image.png](https://raw.githubusercontent.com/JukeBoxK/ped/main/files/c5bbc6ab-1ab6-48de-b66c-426179d7a2a9.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: JukeBoxK/ped#6

**Comment by ziyang27** [comment]
Change the user guide
