### ISSUE TITLE
[PE-D][Tester B] The corruption of JSON file caused the app to stop working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-2/tp#146]
Changing the date of the JSON file to be invalid ones, like 29-02-2023 in one of the contact, causes the app to crash on launch and not work entirely. Having a corruption check during the initialization process and deleting the entire .json file if there is an invalid entry, could be one way to handle this.

_changing date to be invalid_

![image.png](https://raw.githubusercontent.com/JukeBoxK/ped/main/files/90bf0a7b-3410-4d9d-a293-20d8569f0cdb.png)

_Windows PowerShell showing error message on launch_

![image.png](https://raw.githubusercontent.com/JukeBoxK/ped/main/files/81e207bc-8ded-4ee6-b6dc-920468d7d12f.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: JukeBoxK/ped#7

**Comment by ziyang27** [comment]
Pending
