### ISSUE TITLE
On upcoming page, unable to run `list` command to get back all contact

### ISSUE THREAD

**Issue by Colex2000** [AY2324S2-CS2103T-F13-2/tp#97]
After I run `upcoming` and add some guy `add n/yun chao p/90909090 e/yunchao@gmail.com a/AMK street 122, block 10`, the list is not showing the full contact list. Also, I am unable to run `list` to get back to the full contact list although the GUI message says "Listed all persons".

**Comment by tanyunchao** [comment]
@Colex2000 does the same bug occur for your `lastcontact` command?

**Comment by Colex2000** [comment]
> @Colex2000 does the same bug occur for your `lastcontact` command?

Nope, it doesn't.
